name: Forex Scanner Real

on:
  workflow_dispatch:

  schedule:
    - cron: '*/5 * * * *'

jobs:
  scanner:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          npm install

      - name: Create Firebase Key
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > serviceAccount.json

      - name: Run Scanner
        env:
          API_KEY_1: ${{ secrets.TWELVEDATA_KEY_1 }}
          API_KEY_2: ${{ secrets.TWELVEDATA_KEY_2 }}
          API_KEY_3: ${{ secrets.TWELVEDATA_KEY_3 }}
        run: |
          node scripts/scanner.js
