name: Test TechnicalIndicators

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm install

      - name: Test Library
  run: |
          node - <<'EOF'
          const { EMA, RSI, ADX, ATR } = require("technicalindicators");

               console.log("EMA:", typeof EMA.calculate);
               console.log("RSI:", typeof RSI.calculate);
               console.log("ADX:", typeof ADX.calculate);
               console.log("ATR:", typeof ATR.calculate);

               console.log("EMA EXEMPLO:");
               console.log(EMA.calculate({
               period: 3,
               values: [1,2,3,4,5]
          }));

              console.log("RSI EXEMPLO:");
              console.log(RSI.calculate({
              period: 3,
              values: [1,2,3,4,5,6]
          }));
EOF
